H: 100
W: 100
N: 50
M: 2
T: 200
ds: 1.0
dt: 1.0
sigma: 0.3
kappa_trail: 0.7
kappa_home: 1.2
alpha: 0.15
lam: 0.02
deposit: 0.8
pick_radius: 2.0
nest_radius: 2.0
food_per_source: 200
env_stride: 5
layout: corners
seed: 1234
